version: "2"
run:
  timeout: 5m
  allow-parallel-runners: true
  go: "1.26"

linters:
  enable:
    - copyloopvar
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
