---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - auth.litellm.ai
  resources:
  - users
  - virtualkeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auth.litellm.ai
  resources:
  - users/finalizers
  - virtualkeys/finalizers
  verbs:
  - update
- apiGroups:
  - auth.litellm.ai
  resources:
  - users/status
  - virtualkeys/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
