apiVersion: litellm.litellm.ai/v1alpha1
kind: LiteLLMInstance
metadata:
  name: litellm-example
  namespace: litellm
spec:
  redisSecretRef:
    nameRef:  redis-secret
    keys:
      hostSecret: host
      portSecret: 5555
      passwordSecret: password
  databaseSecretRef:
    nameRef:  postgres-secret
    keys:
      hostSecret: host
      passwordSecret: password
      usernameSecret: username
      dbnameSecret: dbname
  modelList:
    - modelName: gpt-3.5-turbo
      liteLLMParams:
        apiBase: https://api.litellm.ai/v1
        model: gpt-3.5-turbo
        maxBudget: "1000"
        maxRetries: 3
        tpm: 60
        rpm: 20
        regionName: us-west-2
        apiKey:
          nameRef: api-key-secret
          keys:
            apiKey: api-key
      modelInfo:
        description: "GPT-3.5 Turbo model for general-purpose tasks"
        version: "1.0"
