apiVersion: litellm.litellm.ai/v1alpha1
kind: LiteLLMInstance
metadata:
  name: litellm-example
  namespace: litellm
spec:
  redisSecretRef:
    nameRef:  redis-secret
    keys:
      hostSecret: host
      portSecret: port
      passwordSecret: password
  databaseSecretRef:
    nameRef:  postgres-secret
    keys:
      hostSecret: host
      passwordSecret: password
      usernameSecret: username
      dbnameSecret: dbname
  modelList:
  - modelName: azure-gpt-4o
    requiresAuth: true
    identifier: gpt-east-us-prod
    modelCredentials:
      nameRef: bedrock-model-credentials
      keys:
        awsAccessKeyId: awsAccessKeyId
        awsSecretAccessKey: awsSecretAccessKey
    liteLLMParams:
      model: "azure/gpt-4o"
      customLLMProvider: "azure"
  - modelName: azure-gpt-4o
    requiresAuth: false
    identifier: gpt-west-eu-prod
    liteLLMParams:
      model: "azure/gpt-4o"
